# Site settings
title: Pushing Through the Awfulness
email: gatorpazz@gmail.com
description: Much ado about surviving the pain and misery of a coding boot camp, which I haven't quite yet survived yet.
url: "http://gloryofgatorpazz.me" # the base hostname & protocol for your site
twitter_username: gatorpazz
github_username:  gatorpazz
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Michael Pascuzzi
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
